[[Rule]]
Name = "Material"
Priority = 1
Version = 1
InputFilters = [
    { Repo = "assets", PathPattern = "*.mat.json" }
]
DepFile = { Path = '{ Repo:cooking }{ Path }.dep', Format = 'AssetCooker' }
CommandLine = 'cooker.exe mat "{ Path }" "{ Repo:assets }" "{ Repo:cooking }"'

[[Rule]]
Name = "3D"
Priority = 1
Version = 0
InputFilters = [
    { Repo = "assets", PathPattern = "*.fbx" }
]
DepFile = { Path = '{ Repo:cooking }{ Path }.dep', Format = 'AssetCooker' }
CommandLine = 'cooker.exe fbx "{ Path }" "{ Repo:assets }" "{ Repo:cooking }"'