#include "./bitvector.cpp"
#include "./game_input.cpp"
#include "./input_queue.cpp"
#include "./log.cpp"
#include "./main.cpp"
#include "./poll.cpp"
#include "./sync.cpp"
#include "./timesync.cpp"
// #include "./platform_linux.cpp"
#include "./platform_windows.cpp"
#include "./network/udp.cpp"
#include "./network/udp_proto.cpp"
#include "./backends/p2p.cpp"
#include "./backends/spectator.cpp"
#include "./backends/synctest.cpp"
